[mypy]
python_version = 3.9
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_no_return = True
warn_unreachable = True

[mypy-tests.*]
ignore_errors = True

[mypy-example.api.*]
ignore_missing_imports = True

[mypy-example.http.*]
ignore_missing_imports = True

[mypy-flask.*]
ignore_missing_imports = True

[mypy-authlib.*]
ignore_missing_imports = True

[mypy-websockets.*]
ignore_missing_imports = True

[mypy-httpx.*]
ignore_missing_imports = True
